export const CREATE_POKEMON = "CREATE_POKEMON";
export const GET_POKEMON = "GET_POKEMON";
export const UPDATE_POKEMON = "UPDATE_POKEMON";
export const DELETE_POKEMON = "DELETE_POKEMON";
export const SELECT_POKEMON = "SELECT_POKEMON";
export const CLEAR_POKEMON = "CLEAR_POKEMON";
export const DELETE_SELECTED_POKEMON = "DELETE_SELECTED_POKEMON";